#!/bin/sh

config="$1"
src="$2"
dest="$3"
fromfile="$HOME/.config/dobackups/$config"
synctreedir="$HOME/.cache/dobackups/synctrees/$config"

mkdir -p $synctreedir

for d in $(cat $fromfile); do
	efromfile=$(mktemp /tmp/dobackups/efromfile.XXXXXX)
	echo "$d" > efromfile

	touch $synctreedir/$d

	if [[ "$(diff <(ls -laR $src/$d) $synctreedir/$d)" != "" ]]; then
		rsync -vlrut --progress --delete --files-from=$efromfile $src $dest
	fi
	rsync -vlrut --progress --delete --files-from=$efromfile $dest $src

	ls -laR $src/$d > $synctreedir/$d
	rm $efromfile
done
