#!/bin/sh

config="$1"
src="$2"
dest="$3"
fromfile="$HOME/.config/dobackups/$config"
synctreedir="$HOME/.cache/dobackups/synctrees/$config"

mkdir -p $synctreedir
touch $synctreedir/old

if [[ "$(diff <(ls -laR $src) $synctreedir/old)" != "" ]]; then
	rsync -vlrut --progress --delete --files-from=$fromfile $src $dest
fi
rsync -vlrut --progress --delete --files-from=$fromfile $dest $src

ls -laR $src > $synctreedir/old
