#!/bin/sh

config="$1"
src="$2"
dest="$3"
fromfile="$HOME/.config/dobackups/$config"
synctreedir="$HOME/.cache/dobackups/synctrees/$config"

mkdir -p $synctreedir
mkdir -p /tmp/dobackups

for d in $(cat $fromfile); do
	efromfile=$(mktemp /tmp/dobackups/efromfile.XXXXXX)
	echo "$d" > $efromfile

	touch $synctreedir/$d

	curtreesync=$(mktemp /tmp/dobackups/curtreesync.XXXXXX)
	ls -laR "$src""$d" > $curtreesync

	echo "BEG DIFF"
	diff $curtreesync $synctreedir/$d
	echo "END DIFF"

	if [[ "$(diff $curtreesync $synctreedir/$d)" != "" ]]; then
		rsync -vlrut --progress --delete --files-from=$efromfile $src $dest
	else
		rsync -vlrut --progress --delete --files-from=$efromfile $dest $src
	fi
	ls -laR "$src""$d" > $synctreedir/$d

	ls -laR "$src""$d" > $curtreesync
	echo "BEG DIFF"
	diff $curtreesync $synctreedir/$d
	echo "END DIFF"

	rm $curtreesync
	rm $efromfile
done
